### ISSUE TITLE
Error while rendering item in JEI gui

### ISSUE THREAD

**Issue by PickleGaming32** [dragon-forge/OnlineDisplays#1]
Whenever I search for online displays in the JEI panel my game crashes, saying that it couldn't render the mod's item. 

Any help appreciated.

Cheers.

[report.txt](https://github.com/dragon-forge/OnlineDisplays/files/11951218/report.txt)

**Comment by Zeitheron** [comment]
Thanks for your report and sorry for the delay.
I have made a mixin instead of a method call since it seems like it might not be present for all versions of Forge.
