### ISSUE TITLE
Cannot access in survival even when config is set to "true"

### ISSUE THREAD

**Issue by Xiarno** [dragon-forge/OnlineDisplays#2]
Playing in 1.19.2. 
The config has been changed to "True", but I still cannot interact with them in survival.

**Comment by Zeitheron** [comment]
Inspecting the issue, sorry for the delay.

**Comment by Zeitheron** [comment]
Couldn't find any issues, but I added a few safeguards for server owners so that the sent packets for modifying a display will actually check if a player is capable of editing a display.

**Comment by Zeitheron** [comment]
This is how it's going to look for when you can not use a display.

![image](https://github.com/dragon-forge/OnlineDisplays/assets/38943617/bf1b2ac3-135b-4a9a-a3ad-8d29244bc503)
